Tabs support for feature-flagged parts
netdata/netdata-ui pull request #124
Opened 2020-09-09 16:39 UTC by Azein

In expressions like
```
{isFeatureAvailable() && <Tab ..... />}
```
value `false` will be included in React children array, which messes up useBuildTabs hook, resulting in unreachable feature-flagged tabs, if there are multiple of them and some are enabled and some not.

This PR offers a solution to allow usage of such simple expressions as mentioned above, with persisting indices without actually including "false" part into navs.

2020-09-09 16:41 UTC, builat approved these changes

2020-09-09 20:38 UTC, novykh requested changes
By looking at it (currently on my phone, will check it thoroughly tomorrow) both implementations seem to do the same thing. Not pushing falsey tabs to the children array. Thus, I dont think there is any need to change this, unless of course there is indeed a problem. Can you provide a test case maybe failing with the first implementation but passing with the second? Lets talk tomorrow

2020-09-09 20:38 UTC, novykh commented on src/components/tabs/tabs-hooks.tsx
> -      const { props } = tab
I dont see any difference with the changes you made. Line 19 that you removed returns fast for falsy tabs and do not push children. Can you elaborate more about this change?

2020-09-10 11:58 UTC, novykh approved these changes

2020-09-10 12:24 UTC, merged