Add test coverage report
netdata/netdata-ui pull request #291
Opened 2022-02-25 14:51 UTC by ivangergo3

Added similar test-coverage report as we have in "cound-frontend"

So from now on, all tests will be executed when a pull request is being created.

And we will publish the results into google cloud, so we can check the current status [here](https://github.com/netdata/test-automation/wiki/Netdata-Test-Coverage-Report)

Could you please check this change? And if you have any concerns let me know

2022-02-28 14:56 UTC, novykh requested changes

2022-02-28 14:56 UTC, novykh commented on .github/workflows/tests.yml
> +  pull_request:
Do it only on push on master.

2022-03-03 10:29 UTC, burbuli8ra approved these changes
LGTM, but please wait for 1 more approval before merging!
Also, I see that this branch is out of sync with the base! Maybe you could do a rebase to avoid conflicts! 😄

2022-03-04 10:15 UTC, novykh approved these changes

2022-03-04 14:50 UTC, ivangergo3 commented
@jjtsou do you think it can be merged now?

2022-03-08 08:52 UTC, jjtsou approved these changes

2022-03-08 10:41 UTC, ivangergo3 commented
@novykh  do you think it can be merged now?

2022-03-08 10:46 UTC, novykh commented
Yes whatever is approved can be merged.

2022-03-08 12:07 UTC, merged